return function(use)
  use({ 'ofirgall/ofirkai.nvim' })
  use({ 'mbbill/undotree' })
  use({ "windwp/nvim-autopairs" })
  use({ 'jose-elias-alvarez/null-ls.nvim' })
  use({ "folke/trouble.nvim" })
  use({ "danymat/neogen" })
  use({ "hrsh7th/cmp-buffer" })
  -- use({ "p00f/clangd_extensions.nvim" })
end
